vich_uploader:
    db_driver: orm
    mappings:
        user_profile:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_cover:
            uri_prefix: /images/covers
            upload_destination: '%kernel.project_dir%/public/images/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        guild_blason:
            uri_prefix: /guilds/blasons
            upload_destination: '%kernel.project_dir%/public/guilds/blasons'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        guild_cover:
            uri_prefix: /guilds/covers
            upload_destination: '%kernel.project_dir%/public/guilds/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

