UPDATE resource SET xp_pet = 1250.0 WHERE name = 'Galet brasillant';
UPDATE resource SET xp_pet = 1250.0 WHERE name = 'Galet acajou';
UPDATE resource SET xp_pet = 500.0 WHERE name = 'Rune Ga Pa';
UPDATE resource SET xp_pet = 405.0 WHERE name = 'Rune Ga Pme';
UPDATE resource SET xp_pet = 375.0 WHERE name = 'Coeur Gelé';
UPDATE resource SET xp_pet = 375.0 WHERE name = 'Alliage Ivre';
UPDATE resource SET xp_pet = 338.0 WHERE name = 'Braguette de Nileza';
UPDATE resource SET xp_pet = 338.0 WHERE name = 'Culotte de Missiz Frizz';
UPDATE resource SET xp_pet = 338.0 WHERE name = 'Incisive de Sylargh';
UPDATE resource SET xp_pet = 338.0 WHERE name = 'Scalp de Klime';
UPDATE resource SET xp_pet = 338.0 WHERE name = 'Bandelette du Comte Harebourg';
UPDATE resource SET xp_pet = 338.0 WHERE name = 'Coeur de Merkator';
UPDATE resource SET xp_pet = 338.0 WHERE name = 'Poche de magma de Grasmera';
UPDATE resource SET xp_pet = 313.0 WHERE name = 'Galet Solaire';
UPDATE resource SET xp_pet = 300.0 WHERE name = 'Cuir Onique';
UPDATE resource SET xp_pet = 281.0 WHERE name = 'Encre du Kralamoure géant';
UPDATE resource SET xp_pet = 254.0 WHERE name = 'Hamatum de Glourséleste';
UPDATE resource SET xp_pet = 254.0 WHERE name = 'Condyle de Fuji Givrefoux';
UPDATE resource SET xp_pet = 254.0 WHERE name = 'Étoffe de Kolosso';
UPDATE resource SET xp_pet = 254.0 WHERE name = 'Étoffe givrée';
UPDATE resource SET xp_pet = 254.0 WHERE name = 'Eclat temporel';
UPDATE resource SET xp_pet = 200.0 WHERE name = 'Fermeture éclair';
UPDATE resource SET xp_pet = 200.0 WHERE name = 'Mycoses gelées';
UPDATE resource SET xp_pet = 200.0 WHERE name = 'Oeil de verre';
UPDATE resource SET xp_pet = 200.0 WHERE name = 'Racine cristalline';
UPDATE resource SET xp_pet = 200.0 WHERE name = 'Boulon neuf';
UPDATE resource SET xp_pet = 196.0 WHERE name = 'Oeil de Korriandre';
UPDATE resource SET xp_pet = 195.0 WHERE name = 'Fragment d''Ougalurette';
UPDATE resource SET xp_pet = 195.0 WHERE name = 'Peau du Bworker';
UPDATE resource SET xp_pet = 161.0 WHERE name = 'Vertèbre d''Obsidiantre';
UPDATE resource SET xp_pet = 153.0 WHERE name = 'Cuir de Tengu Givrefoux';
UPDATE resource SET xp_pet = 130.0 WHERE name = 'Rune Po';
UPDATE resource SET xp_pet = 125.0 WHERE name = 'Galet rutilant';
UPDATE resource SET xp_pet = 125.0 WHERE name = 'Galet boucané';
UPDATE resource SET xp_pet = 120.0 WHERE name = 'Sabot du Minotot';
UPDATE resource SET xp_pet = 120.0 WHERE name = 'Corne du Minotot';
UPDATE resource SET xp_pet = 120.0 WHERE name = 'Cuir du Minotot';
UPDATE resource SET xp_pet = 120.0 WHERE name = 'Laine du Minotot';
UPDATE resource SET xp_pet = 120.0 WHERE name = 'Fémur du Minotot';
UPDATE resource SET xp_pet = 120.0 WHERE name = 'Chaussette du Kimbo';
UPDATE resource SET xp_pet = 120.0 WHERE name = 'Pierre précieuse du Kimbo';
UPDATE resource SET xp_pet = 116.0 WHERE name = 'Scapula de Ben le Ripate';
UPDATE resource SET xp_pet = 96.0 WHERE name = 'Bézoard Ardent de Grozilla';
UPDATE resource SET xp_pet = 96.0 WHERE name = 'Étoffe de Sphincter Cell';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Bec de Dodox';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Sépale de Drosérâle';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Crinière de Krakal';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Molaire de Nessil';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Carapace de Termystique';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Moustache de Frimar';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Malleus de Karkanik';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Ethmoïde de Stalak';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Molaire de Ventrublion';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Cervelle de Verglasseur';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Queue de Brikoglours';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Griffe de Kanimate';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Sternum de Mansordide';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Oreille de Mécanofoux';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Pédoncule de Mérulor';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Dent de Cuirboule';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Coeur d''Empaillé';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Étoffe de Grodruche';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Cervelle de Peunch';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Plume de Cycloïde';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Bec de Granduk';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Pic du Nocturlabe';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Queue de Sinistrofu';
UPDATE resource SET xp_pet = 92.0 WHERE name = 'Bec de Strigide';
UPDATE resource SET xp_pet = 91.0 WHERE name = 'Oeuf de Gobus';
UPDATE resource SET xp_pet = 90.0 WHERE name = 'Oeuf du Mansot Royal';
UPDATE resource SET xp_pet = 88.0 WHERE name = 'Delko du Perkü';
UPDATE resource SET xp_pet = 78.0 WHERE name = 'Queue de Marôdeur';
UPDATE resource SET xp_pet = 78.0 WHERE name = 'Croc de Krokille';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Laine de Glouragan';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Étoffe de Glourmand';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Calcanéus de Meliglours';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Poil de Blérauve';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Oreille de Blérice';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Queue de Blérom';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Étoffe de Croleur';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Queue Magique du Péki';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Étoffe de Péki';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Ambre du Tynril';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Peau lacérée du Tynril';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Écorce du Tynril';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Ambre du Chêne Mou';
UPDATE resource SET xp_pet = 76.0 WHERE name = 'Bourgeon du Chêne Mou';
UPDATE resource SET xp_pet = 75.0 WHERE name = 'Oeil de Fleuro';
UPDATE resource SET xp_pet = 69.0 WHERE name = 'Manubrium de Wolvero';
UPDATE resource SET xp_pet = 68.0 WHERE name = 'Culotte de Harrogant';
UPDATE resource SET xp_pet = 63.0 WHERE name = 'Galet Lunaire';
UPDATE resource SET xp_pet = 60.0 WHERE name = 'Étoile d''Or d''El Piko';
UPDATE resource SET xp_pet = 60.0 WHERE name = 'Testicules du Tanukouï San';
UPDATE resource SET xp_pet = 58.0 WHERE name = 'Caleçon de Cybwork';
UPDATE resource SET xp_pet = 57.0 WHERE name = 'Cornée de Kami Givrefoux';
UPDATE resource SET xp_pet = 56.0 WHERE name = 'Queue du Royalmouth';
UPDATE resource SET xp_pet = 56.0 WHERE name = 'Lamelle de Champbis';
UPDATE resource SET xp_pet = 56.0 WHERE name = 'Langue du Champodonte';
UPDATE resource SET xp_pet = 56.0 WHERE name = 'Trompe de la Tromperelle';
UPDATE resource SET xp_pet = 55.0 WHERE name = 'Caleçon Blanc';
UPDATE resource SET xp_pet = 55.0 WHERE name = 'Caleçon Bleu';
UPDATE resource SET xp_pet = 55.0 WHERE name = 'Caleçon Rouge';
UPDATE resource SET xp_pet = 55.0 WHERE name = 'Caleçon Brun';
UPDATE resource SET xp_pet = 54.0 WHERE name = 'String en Cuir de la Mama Bwork';
UPDATE resource SET xp_pet = 53.0 WHERE name = 'Écorce de Champaknyde';
UPDATE resource SET xp_pet = 51.0 WHERE name = 'Broderie de la Reine des Voleurs';
UPDATE resource SET xp_pet = 51.0 WHERE name = 'Joyau de la couronne du roi Nidas';
UPDATE resource SET xp_pet = 51.0 WHERE name = 'Dé du Chaloeil';
UPDATE resource SET xp_pet = 51.0 WHERE name = 'Aile de Vortex';
UPDATE resource SET xp_pet = 51.0 WHERE name = 'Chaussette du Cyclophandre';
UPDATE resource SET xp_pet = 51.0 WHERE name = 'Pince de Krabouilleur';
UPDATE resource SET xp_pet = 51.0 WHERE name = 'Huile de Pikoleur';
UPDATE resource SET xp_pet = 50.0 WHERE name = 'Oeuf de Crapeur';
UPDATE resource SET xp_pet = 48.0 WHERE name = 'Peau de Skeunk';
UPDATE resource SET xp_pet = 48.0 WHERE name = 'Culotte à l''envers du Roissingue';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Racine d''Abrazif';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Oeil de Dramanite';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Oreille de Fistulor';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Pédoncule de Fongeur';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Pédoncule de Mérulette';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Coquille de Submergé';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Scarabée Chrysonéfritin';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Poil de Maître Pandore';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Peau de Maître Pandore';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Étoffe de Maître Pandore';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Cuir du Minotoror';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Sabot du Minotoror';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Fémur du Minotoror';
UPDATE resource SET xp_pet = 47.0 WHERE name = 'Corne Brûlée du Minotoror';
UPDATE resource SET xp_pet = 46.0 WHERE name = 'Téphra d''Atomystique';
UPDATE resource SET xp_pet = 46.0 WHERE name = 'Artefact de Fumrirolle';
UPDATE resource SET xp_pet = 46.0 WHERE name = 'Sang de Calciné';
UPDATE resource SET xp_pet = 46.0 WHERE name = 'Goulobule rouge';
UPDATE resource SET xp_pet = 45.0 WHERE name = 'Rune Invo';
UPDATE resource SET xp_pet = 44.0 WHERE name = 'Symbole des Obscuranti';
UPDATE resource SET xp_pet = 43.0 WHERE name = 'Chope de Bière';
UPDATE resource SET xp_pet = 43.0 WHERE name = 'Brûlâme encapsulé';
UPDATE resource SET xp_pet = 43.0 WHERE name = 'Poignée du Gorgouille';
UPDATE resource SET xp_pet = 39.0 WHERE name = 'Ulna de Solfataré';
UPDATE resource SET xp_pet = 39.0 WHERE name = 'Radius d''Ouilleur';
UPDATE resource SET xp_pet = 38.0 WHERE name = 'Iris de Boulglours';
UPDATE resource SET xp_pet = 38.0 WHERE name = 'Aile de Gloursaya';
UPDATE resource SET xp_pet = 38.0 WHERE name = 'Corne d''Ombre';
UPDATE resource SET xp_pet = 37.0 WHERE name = 'Peau du Rasboul Majeur';
UPDATE resource SET xp_pet = 37.0 WHERE name = 'Queue emplumée du Rasboul Majeur';
UPDATE resource SET xp_pet = 36.0 WHERE name = 'Oeil de Vigie Pirate';
UPDATE resource SET xp_pet = 36.0 WHERE name = 'Noeud de l''Abrakleur clair';
UPDATE resource SET xp_pet = 35.0 WHERE name = 'Moumoute du Sapeur';
UPDATE resource SET xp_pet = 35.0 WHERE name = 'Bouteille de Bouchonnois';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Vomer d''Apériglours';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Noyau de Protozorreur';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Sel de Baleine';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Epaulette de Dazak Martegel';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Queue de Bethel Akarna';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Patte de Gobosteur';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Borderie de Nileza';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Poil d''aisselle de Missiz Frizz';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Laine de Sylargh';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Plume d''Ilyzaelle';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Moustache de Klime';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Scapula du Comte Harebourg';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Cheveux de Tal Kasha';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Barbe de Merkator';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Broderie d''Eskoglyphe';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Poil de Meno';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Aile de Larve de Koutoulou';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Dentier de Dantinéa';
UPDATE resource SET xp_pet = 34.0 WHERE name = 'Pointe osseuse de Grasmera';
UPDATE resource SET xp_pet = 33.0 WHERE name = 'Cervelle de Solar';
UPDATE resource SET xp_pet = 33.0 WHERE name = 'Pic d''Anerice';
UPDATE resource SET xp_pet = 31.0 WHERE name = 'Coquille de Harpirate';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Huile de Fantimonier';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Sang du Toxoliath';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Slip troué de Dramak';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Pierre du Koulosse';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Testicules de Meulou';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Dents de Meulou';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Mojo du Meulou';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Testicules Magiques du Meulou';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Oeil de Meulou';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Crâne du Dragon Cochon';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Sang de Dragon Cochon';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Dragolait';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Queue de Dragon Cochon';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Défense de Dragon Cochon';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Poil de Dragon Cochon';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Étoffe Magique de Moon';
UPDATE resource SET xp_pet = 29.0 WHERE name = 'Étoffe de Meupette';
UPDATE resource SET xp_pet = 28.0 WHERE name = 'Bave de Champ à Gnons';
UPDATE resource SET xp_pet = 28.0 WHERE name = 'Oeil de Champmane';
UPDATE resource SET xp_pet = 28.0 WHERE name = 'Ventouse du Kralamoure géant';
UPDATE resource SET xp_pet = 27.0 WHERE name = 'Corde du Fancrôme';
UPDATE resource SET xp_pet = 27.0 WHERE name = 'Bouée de Fantomalamère';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Queue de Glourséleste';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Cuir de Fuji Givrefoux';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Griffe de Kolosso';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Poudre glaciale';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Fragment gelé';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Fausse dent de Grozilla';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Poils du Comte Razof';
UPDATE resource SET xp_pet = 25.0 WHERE name = 'Pilule de Rat Pine';
UPDATE resource SET xp_pet = 24.0 WHERE name = 'Pierre Angulaire';
UPDATE resource SET xp_pet = 24.0 WHERE name = 'Peau de Trithon';
UPDATE resource SET xp_pet = 23.0 WHERE name = 'Cuir de Maho Givrefoux';
UPDATE resource SET xp_pet = 23.0 WHERE name = 'Étoffe de Kaniglou';
UPDATE resource SET xp_pet = 23.0 WHERE name = 'Corne de XLII';
UPDATE resource SET xp_pet = 23.0 WHERE name = 'Parasite Aquatique';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Oreille du Fu Mansot';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Poche de charbon de Grasmera';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Étoffe de Choudini';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Bwak Squelettique';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Talon d''achille de l''Abrakleur sombre';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Bourgeon d''Abraknyde Ancestral';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Oeil de Branche Invocatrice';
UPDATE resource SET xp_pet = 22.0 WHERE name = 'Oeil de Branche Soignante';
UPDATE resource SET xp_pet = 21.0 WHERE name = 'Écorce de Floribonde';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Arête géante du Shamansot';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Crâne de Yokaï Givrefoux';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Patte de Korriandre';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Oeil torve de Fricochère';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Écorce de Brouture';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Écorce de Chiendent';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Écorce de Fécorce';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Écorce de Nerbe';
UPDATE resource SET xp_pet = 20.0 WHERE name = 'Mandibule d''Abrakne Irascible';
UPDATE resource SET xp_pet = 19.0 WHERE name = 'Épine d''Ougah';
UPDATE resource SET xp_pet = 19.0 WHERE name = 'Oeil d''Ougah';
UPDATE resource SET xp_pet = 19.0 WHERE name = 'Ongle du Bworker';
UPDATE resource SET xp_pet = 19.0 WHERE name = 'Arakne Irascible Écrasée';
UPDATE resource SET xp_pet = 18.0 WHERE name = 'Huile de Mamansot';
UPDATE resource SET xp_pet = 18.0 WHERE name = 'Patte de Soryo Givrefoux';
UPDATE resource SET xp_pet = 18.0 WHERE name = 'Moustache de Ush';
UPDATE resource SET xp_pet = 18.0 WHERE name = 'Coquille de Krokille';
UPDATE resource SET xp_pet = 18.0 WHERE name = 'Oeil de la Gardienne des Égouts';
UPDATE resource SET xp_pet = 18.0 WHERE name = 'Ambre d''Abraknyde Sombre Irascible';
UPDATE resource SET xp_pet = 17.0 WHERE name = 'Queue de Yomi Givrefoux';
UPDATE resource SET xp_pet = 17.0 WHERE name = 'Défense du Sanglacier';
UPDATE resource SET xp_pet = 17.0 WHERE name = 'Coeur du Mantiscore';
UPDATE resource SET xp_pet = 17.0 WHERE name = 'Coquille du Kaskargo';
UPDATE resource SET xp_pet = 16.0 WHERE name = 'Aile de Mansobèse';
UPDATE resource SET xp_pet = 16.0 WHERE name = 'Dent de Fantômat';
UPDATE resource SET xp_pet = 16.0 WHERE name = 'Scorie d''Obsidiantre';
UPDATE resource SET xp_pet = 16.0 WHERE name = 'Couche de Daïgoro';
UPDATE resource SET xp_pet = 16.0 WHERE name = 'Coco du Bitouf aérien';
UPDATE resource SET xp_pet = 16.0 WHERE name = 'Kristalite';
UPDATE resource SET xp_pet = 15.0 WHERE name = 'Queue du Boufmouth légendaire';
UPDATE resource SET xp_pet = 15.0 WHERE name = 'Laine de Tengu Givrefoux';
UPDATE resource SET xp_pet = 15.0 WHERE name = 'Oeil du Père Ver';
UPDATE resource SET xp_pet = 15.0 WHERE name = 'Étoffe de Maho Firefoux';
UPDATE resource SET xp_pet = 15.0 WHERE name = 'Tresse du Poolay';
UPDATE resource SET xp_pet = 14.0 WHERE name = 'Défense du Phossile';
UPDATE resource SET xp_pet = 14.0 WHERE name = 'Carapace de Ver des Sables';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Bec du Timansot';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Oeil de Boufmouth de guerre';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Gland de l''Ecumouth';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Galet Saisonnier';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Galet bistré';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Galet cramoisi';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe du Fauchalak';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Boomerang du Maître Koalak';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Poils de Barbe du Warko Violet';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Léopardo';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Maho Firefoux';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Pandikaze';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Pandore';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Pandule';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Soryo Firefoux';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Tanukouï San';
UPDATE resource SET xp_pet = 13.0 WHERE name = 'Étoffe de Fantôme Yokai Firefoux';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Poil de Ben le Ripate';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Dent de Smilomouth';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Griffe de Buboxor';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Oeil de Harpille';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Serre d''Ikargn';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Corne de Méjaire';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Fémur de Koalak Farouche';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Fiole de fumée de Nelween';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Méga Pierre du Craqueleur Légendaire';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Ethmoïde du Minotot';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Corne de Mominotor';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Corne de Scaratos';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Sphénoïde du Kimbo';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Perruque du Kimbo';
UPDATE resource SET xp_pet = 12.0 WHERE name = 'Pourdre explosive de Gourlo';
UPDATE resource SET xp_pet = 11.0 WHERE name = 'Clavicule de Boufmouth';
UPDATE resource SET xp_pet = 11.0 WHERE name = 'Peau de Chevaucheur Koalak';
UPDATE resource SET xp_pet = 11.0 WHERE name = 'Boomerang du Koalak Sanguin';
UPDATE resource SET xp_pet = 11.0 WHERE name = 'Queue de Koalak Sanguin';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Plume du Mansot Royal';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Aquarakne de Crânonier';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Protection de Funespadon';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Bout d''Armure de Macrab';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Pointe de Lance de Tournoyé';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Chair de Zombruth';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Crâne magique de Magouille';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Boule en or de Piloztère';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Plume du Cavalier';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Sceau du Roi Joueur';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Pique du Soldat';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Gilet du Valet';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Plume de Brabuzar';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Dent de Bandleth';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Fragment de Chakanoubis';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Oreille de Griffotep';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Grenat de Momistik';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Paupière Dorée de Rykaon';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Sang de Harpo';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Dent de Tilamproie';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Flûte de Klûtiste';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Épine de Diondin';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Épine Dorsale de Grozilla';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Place de Concert de Diamantine';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Journal Intime d''Émeraude';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Pense-bête de Rubise';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Shampooing au Kaliptus de Saphira';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Peau de Sphincter Cell';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Oreille de Sphincter Cell';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Fémur de Sphincter Cell';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Langue de Hacharné';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Oeil de Halbardent';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Dent de Klémort';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Grenade de Moribombe';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Vertèbre de Trépavois';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Ongle de Goulafre';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Oeil de Gouligane';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Poils de Goultime';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Aile de Kérigoule';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Nez de Pipisteuse';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Trompe de Minoskito';
UPDATE resource SET xp_pet = 10.0 WHERE name = 'Bâton du Kilibriss';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Poils de barbe de Barbélier';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Fronde de Boufbos';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Jambière de Kasrok';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Armure de Tanklume';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Dent de Vatenbière';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Fragment de pépite de Sakaï';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Pierre du Courtilieur';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Bois de Gobus';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Estomac du Perkü';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Plume de Dodox';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Bracée de Drosérâle';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Canine de Krakal';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Bave de Nessil';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Patte de Termystique';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Stapes de Frimar';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Sang de Karkanik';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Incisive de Stalak';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Sang de Ventrublion';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Incus de Verglasseur';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Maxillaire de Brikoglours';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Canine de Kanimate';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Bec de Mansordide';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Astragale de Mécanofoux';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Volve de Mérulor';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Cendres de Chause';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Pince de Crâme';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Fragment d''Ectorche';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Restes d''Esprigné';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Oeil de Feutôme';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Cuir de Cuirboule';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Cuir d''Empaillé';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Cuir de Grodruche';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Oeil de Harrogant';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Cuir de Peunch';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Oeil de Cycloïde';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Plume de Granduk';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Aile de Nocturlabe';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Aile de Sinistrofu';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Griffe de Strigide';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Coeur du Capitaine Ekarlatte';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Masque de la Violence';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Masque de la Vivacité';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Masque du Vide';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Masque de la Vengeance';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Masque du Vice';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Jus de Cacterre';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Étoffe de Soryo Firefoux';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Lait de Porsalu';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Coco du Bitouf des Plaines';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Coeur de pierre poli';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Bec du Kido';
UPDATE resource SET xp_pet = 9.0 WHERE name = 'Crinière fleurie';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Cuir de Glouragan';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Incisive de Glourmand';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Queue de Meliglours';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Cuir de Bouftonmouth';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Tuf de Mofette';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Griffe de Blérauve';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Molaire de Blérice';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Omoplate de Blérom';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Oreille de Croleur';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Péroné du Marôdeur';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Rune Pa Ré Pa';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Rune Pa Ré Pme';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Rune Pa Ret Pa';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Rune Pa Ret Pme';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Éclat Obscur';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Boue Vénérable';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Flaque Vénérable';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Cendres Vénérables';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Poudre Vénérable';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Fumée Vénérable';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Oreille de Bouledogre';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Élastique de Gobvious';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Corne de Rhinoféroce';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Bave de Brokouillon';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Queue de Chevrotine';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Flèche de Crâmbo';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Os de Nemroz';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Sang de Viandargh';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Coiffe déchiquetée de Drakoalak';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Os de Mama Koalak';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Cervelle de Bouftou des Cavernes';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Testicules de Cocholou';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Mojo de Mergranlou';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Testicules Magiques de Muloubard';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Scalp de Mulounoké';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Corne de Déminoboule';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Pierre de Serpiplume';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Cagoule du Kanniboul Ebil';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Boule polie';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Tibia du Guerrier Zoth';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Braguette du Maître Zoth';
UPDATE resource SET xp_pet = 8.0 WHERE name = 'Écusson du Sergent Zoth';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Antenne de Bacterrib';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Patte de Tabacille';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Oeil de Verminocule';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Coquille de Virustine';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Oreille de Fleuro';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Queue de Wolvero';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Pixel de Fraktale';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Poil de Péki';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Étoffe de Yokai Firefoux';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Étoffe de Pandore';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Calice du Tynril';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Pistil du Tynril';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Rotule du Disciple Zoth';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Écorce du Chêne Mou';
UPDATE resource SET xp_pet = 7.0 WHERE name = 'Racine du Chêne Mou';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Laine du Royalmouth';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Coeur de Crapeur';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Pierre de Mofette';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Incisive de Kami Givrefoux';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Écorce d''Abrazif';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Lamelle de Dramanite';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Volve de Fistulor';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Volve de Fongeur';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Lamelle de Mérulette';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Glande du Pounicheur';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Barbe de Seith';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Pagne de Trantroa';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Dent de Trezz';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Peau de Vindeux';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Venin d''Éperfide';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Pince de Lucrane';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Dard de Morfrelon';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Aile de Puceronde';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Patte de Scoliopode';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Relique du Kimbo';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Picot d''El Piko';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Avoine Magique';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Peau de Roukouto';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Peau de Tivelo';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Poils de Tanukouï San';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Peau de Tanukouï San';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Triquetrum du Maître Pandore';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Poil de Bworkette';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Étoffe Corailleuse';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Corail Magistral';
UPDATE resource SET xp_pet = 6.0 WHERE name = 'Toile d''Abrakne Sombre';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Pierre d''Atomystique';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Pierre de Fumrirolle';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Rune Cri';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Rune Pa So';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Rune So';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Épaulette de Bourôliste';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Chouchou de Doublure';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Piège désamorcé de Mâchassin';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Mèche de bombe de Terristocrate';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Sourcil de Barbétoal';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Corne de Kamasterik';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Dent de Lévitrof';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Morceau de clef de Paspartou';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Touffe de cheveux de Soissanth';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Relique du Tynril';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Pic de Pikténia';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Ceinture de la Dame';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Barbe du Cyclophandre';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Carapace de Krabouilleur';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Pic de Pikoleur';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Queue de Mantaze';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Patte de Li-Fo';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Moustache de Rilur';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Oeil de Krokille';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Bandelette du Guerrier Koalak';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Poil de Skeunk';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Écorce de Liroye Merline';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Bandeau troué d''Air';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Bandeau troué d''Eau';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Bandeau troué de Feu';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Bandeau troué de Terre';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Boulon de Cybwork';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Furoncle de la Mama Bwork';
UPDATE resource SET xp_pet = 5.0 WHERE name = 'Tourbe séchée de Tourbassingue';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Poils de Boulglours';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Antenne de Gloursaya';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Étoffe de Vigie Pirate';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Résidu de Solfataré';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Peau d''Ouilleur';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Do Air';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Do Cri';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Do Eau';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Do Feu';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Do Neutre';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Do Pou';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Do Terre';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Fui';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Pi';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Pa Tac';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Rune Ra Sa';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Broderie de Malléfisk';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Poil de Chacrebleu';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Collier de Chakichan';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Oreille de Chargus';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Queue de Chasquatch';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Dent de Rat Blanc';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Étoffe de Rat Blanc';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Peau de Rat Blanc';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Peau de Rat Noir';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Cubitus de Rat Noir';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Étoffe de Rat Noir';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Fragment du Gorgouille';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Laine du Minotoror';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Poils du Minotoror';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Kole';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Faux menton du Bourbassingue';
UPDATE resource SET xp_pet = 4.0 WHERE name = 'Étoffe du Roissingue';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Oreille d''Apériglours';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Sternum de Chachachovage';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Bec de Gélikan';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Patte de Rat Bougri';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Pince du Fancrôme';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Coquille de Fantimonier';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Queue de Fantomalamère';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Mât de Fantômat';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Écaille de Harpirate';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Oreille de Gobosteur';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Oeil de Sapeur';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ré Pa';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ré Per Air';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ré Per Eau';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ré Per Feu';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ré Per Neutre';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ré Per Terre';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ré Pme';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ret Pa';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Rune Ret Pme';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Biscuit de chance';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Sablier miniature';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Queue de Mère Veilleuse';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Peau de Métaphorreur';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Corne de Père Phorreur';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Griffe de Phorrêveur';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Oeil de Phozami';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Relique du Rasboul Majeur';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Sable Fin';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Cuir d''Eskoglyphe';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Pince de Crabe Yoloniste';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Écaille de Gambaf';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Bave de Mol Usk';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Tentacule de Grofond';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Tentacule de N''Yalg';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Oeil de Shokkoth';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Encre de Poulpée';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Lanterne de Tourthon';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Trident de Tryde';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Chaussette trouée de Dramak';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Poils de Barbe de Dragodinde';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Tresse du Koulosse';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Oeil de Crowneille';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Kolérat Mort';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Collier Cassé de Macien';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Viscères de Scorbute';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Racine Magique de Bambouto Sacré';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Noeud de Marin';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Souche de l''Abrakleur clair';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Barbe inexistante du Barbroussa';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Touffe rousse du Flib';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Humérus du Sparo';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Sourcil du Rasboul majeur';
UPDATE resource SET xp_pet = 3.0 WHERE name = 'Plume du Rasboul Majeur';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Queue du Fu Mansot';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Duvet de Mamansot';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Peau de Mansobèse';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Poil de barbe du Shamansot';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Laine de Boufmouth légendaire';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Oeil de Crabe Hijacob';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Peau de Pataugerme';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Larme de Givrefoux';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Laine de Maho Givrefoux';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Oreille de Soryo Givrefoux';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Laine de Yokaï Givrefoux';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Malléole de Yomi Givrefoux';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Oreille percée du Fricochère';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Oreille de Kaniglou';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Cuir du Sanglacier';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Rune Ra Pi Per';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Rune Ra Pui';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Tête de mort';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Kamatrix';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Slip d''Elsoummo';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Sacoche de Kartouche';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Foulard de Milimaître';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Os de Sramouraï';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Bandelette de Tromblion';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Dent de Chakaroze';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Pixel de Brikablak';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Pixel d''Éklatleth';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Pixel de Farfacette';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Pixel de Gromorso';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Relique de Gourlo le Terrible';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Carapace du Mantiscore';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Parchemin de Cactana';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Fleur de Cactiflore';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Moustaches de Cactoblongo';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Maraca de Lévito';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'String de Pampactus';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Dent de Cycloporth';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Patte de Masticroc';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Langue de Morsquale';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Peau de Trémorse';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Écaille de Grasmera';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Écaille de Grozilla';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Boue Mature';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Flaque Mature';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Cendres Matures';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Poudre Mature';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Fumée Mature';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Peau de Koalak Immature';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Boomerang du Warko Marron';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Patte de la Gardienne des Égouts';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Oeil de Rat Masseur';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Queue de Rat Pine';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Poil de Rat Brâkmarien';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Fibre de Chanvre';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Faux Visage de Choudini';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Pommeau d''Epée';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Scalp de Meulou';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Étoffe du Mulou';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Poils de Kitsou Nufeu';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Groin de Dragon Cochon';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Poils de Moon';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Peau de Moon';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Barbe du Chouque';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Rembourrage de Meupette';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Carpelle de Brouture';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Graine de l''Abrakleur sombre';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Bractée de Chiendent';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Calice de Fécorce';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Étamine de Floribonde';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Sépale de Nerbe';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Racine d''Abraknyde Ancestral';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Ambre Ancestral';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Écorce d''Abraknyde Ancestral';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Bois Envoûté';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Patte d''Abrakne Irascible';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Doigt de Branche Invocatrice';
UPDATE resource SET xp_pet = 2.0 WHERE name = 'Feuille de Branche Soignante';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Plume du Timansot';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Laine de Boufmouth';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corne de Boufmouth de guerre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Oreille de Bouftonmouth';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Poil de Chachachovage';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Pince de Crabe Hijacob';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Plume de Gélikan';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Étoffe de Rat Bougri';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Queue d''Ecumouth';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poil de Smilomouth';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune Age';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune Cha';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune de chasse';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Air';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Cri';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Eau';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Feu';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Neutre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Per Ar';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Per Di';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Per Mé';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Per So';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Pou';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Ren';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Do Terre';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune Fo';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Fui';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune Ine';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune Ini';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Rune Pa Age';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Rune Pa Cha';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Rune Pa Fo';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Rune Pa Ine';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Rune Pa Ini';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Pa Pi Per';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Rune Pa Pod';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Pa Prospe';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Pa Ré Air';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Pa Ré Cri';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Pa Ré Eau';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Pa Ré Feu';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Pa Ré Neutre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Pa Ré Pou';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Pa Ré Terre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Pa Sa';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Rune Pa Vi';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Pi';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Pi Per';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune Pod';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Rune Prospe';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Pui';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ra Age';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ra Cha';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ra Fo';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ra Ine';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ra Ini';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ra Pod';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ra Vi';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Ré Air';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Ré Cri';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Ré Eau';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Ré Feu';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Ré Neutre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ré Per Di';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Ré Per Mé';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Ré Pou';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Rune Ré Terre';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Rune Sa';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune Tac';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Rune Vi';
UPDATE resource SET xp_pet = 1.25 WHERE name = 'Pépite';
UPDATE resource SET xp_pet = 1.25 WHERE name = 'Rose des sables';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Palpe de Pikbul';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Peau de Gériatique';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Épine de Grath';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Oeil de Morcac';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Patte de Pupuce';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Jeton du Chazino du Grand Jeu';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corne de Berserkoffre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corde de Boursoin';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Langue de Mimikado';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Moustache précieuse';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Antenne de Trésantène';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Jeton du Chazino Matougarous';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Pixel de Segmantid';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Relique du Corailleur Magistral';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Boule de Boulépique';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Queue de Fennex';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Oeil de Léolhyène';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Écailles d''Ouroboulos';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Queue de Scordion Bleu';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rune de Signature';
UPDATE resource SET xp_pet = 0.0012 WHERE name = 'Plume de Piou Bleu';
UPDATE resource SET xp_pet = 0.0012 WHERE name = 'Plume de Piou Jaune';
UPDATE resource SET xp_pet = 0.0012 WHERE name = 'Plume de Piou Rose';
UPDATE resource SET xp_pet = 0.0013 WHERE name = 'Plume de Piou Rouge';
UPDATE resource SET xp_pet = 0.0013 WHERE name = 'Plume de Piou Vert';
UPDATE resource SET xp_pet = 0.0012 WHERE name = 'Plume de Piou Violet';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Boue Juvénile';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Jaune d''Oeuf de Krokille';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Flaque Juvénile';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Cendres Juvéniles';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Poudre Juvénile';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Fumée Juvénile';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Boue Novice';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Flaque Novice';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Cendres Novices';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Poudre Novice';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Fumée Novice';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Patte de Bouledogre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Plume de Gobvious';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Dent de Molette';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Oreille de Rhinoféroce';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Serrure du Coffre des Forgerons';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Sceau Royal Contrefait';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Pièce du Trésor du Badoul';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Sac à Patates Sombre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Pièce du Puzzle de la Griffe';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Sac à Patates Clair';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Tatouage de Mauvais Garçon';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Graine de la Discorde';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Chaînes Brisées';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Bougie du Mineur Sombre';
UPDATE resource SET xp_pet = 0.07692 WHERE name = 'Bourse Suspecte';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Pic de Dragodinde';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Lait de Dragodinde';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Aile de Dragodinde';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Queue de Dragodinde';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Aile de Dragodinde Dorée';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Pic de Dragodinde Dorée';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Dent de Dragodinde';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Pic de Dragodinde Rousse Sauvage';
UPDATE resource SET xp_pet = 0.1 WHERE name = 'Sueur de dragodinde';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Queue de Dragodinde Rousse Sauvage';
UPDATE resource SET xp_pet = 0.02 WHERE name = 'Feuille de Kaliptus';
UPDATE resource SET xp_pet = 0.02 WHERE name = 'Fleur de Kaliptus';
UPDATE resource SET xp_pet = 0.2 WHERE name = 'Étoffe de Dok Alako';
UPDATE resource SET xp_pet = 0.2 WHERE name = 'Pierre Médicinale';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Boomerang du Dok Alako';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Peau de Drakoalak';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Crâne d''Aventurier';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Tibia de Koalak Fossoyeur';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Guerrier Koalak';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Koalak Coco';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Foulard de Koalak Farouche';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Koalak Forestier';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Koalak Griotte';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Koalak Indigo';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Koalak Reinette';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Houpette de Koalak Sanguin';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Peau de Maître Koalak';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Cubitus de Momie Koalak';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Os de Pékeualak';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Peau de Piralak';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Couche usagée de Warko Violet';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Laine du Boufcoul';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Cuir du Boufcoul';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Corne du Boufcoul';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Boomerang Abîmé de Diamantine';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Dédicace de Skeunk pour Émeraude';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Touffe de Poils de Rubise';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Épingle à Cheveux de Saphira';
UPDATE resource SET xp_pet = 0.06667 WHERE name = 'Oeil d''Arakmuté';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Peau Égrotante';
UPDATE resource SET xp_pet = 0.06667 WHERE name = 'Intestin d''araknosé';
UPDATE resource SET xp_pet = 0.06667 WHERE name = 'Bec du Tofu';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Puces Sauteuses';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Bave Empoisonnée';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Oreille de Guerrier Mental';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Peau de Rat';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Crocs de Rats';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Rondelles de Milirat Strubien';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Peau de Ramane d''Égoutant';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Peau de Rat';
UPDATE resource SET xp_pet = 0.11111 WHERE name = 'Laine de Ramane Strubien';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Oeil de Ramane Strubien';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Poil de Rat d''Égoutant';
UPDATE resource SET xp_pet = 0.2 WHERE name = 'Queue de Rat d''Hyoactif';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Cuir de Scélérat Strubien';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Crinière de Scélérat Strubien';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Bandelettes';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Bombe de Graboule';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Bourgeon de Pirolienne';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Couteau de Roukouto';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Roue de Tivelo';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Duvet de Nelween';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Oreilles de Croc Gland';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Queue de Croc Gland';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Papatte de Croc Gland';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Poils de Croc Gland';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Croquette';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Plume de Crowneille';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Moustache de Kolérat';
UPDATE resource SET xp_pet = 0.2 WHERE name = 'Poil d''Ouginak';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Babines de Macien';
UPDATE resource SET xp_pet = 0.2 WHERE name = 'Chaîne de l''Ouginak';
UPDATE resource SET xp_pet = 0.2 WHERE name = 'Pince de Scorbute';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Queue de scorbute';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Carapace de Scorbute';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Patte de Scorbute';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Oeil de Cocholou';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Canine de Mergranlou';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Queue du Mulou';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Griffe de Muloubard';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Poils de Mulounoké';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Léopardo';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Maho Firefoux';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Pandikaze';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Pandore';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Pandule';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Soryo Firefoux';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Tanukouï San';
UPDATE resource SET xp_pet = 1.3 WHERE name = 'Os de Fantôme Yokai Firefoux';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Poils de Léopardo';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Peau de Léopardo';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Poils de Maho Firefoux';
UPDATE resource SET xp_pet = 1.59 WHERE name = 'Peau de Maho Firefoux';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Peau de Soryo Firefoux';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Poils de Soryo Firefoux';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Poils de Yokai Firefoux';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Peau de Yokai Firefoux';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Peau de Kitsou Nae';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Kitsou Nae';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Peau de Kitsou Nakwa';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Kitsou Nakwa';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Peau de Kitsou Nere';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Kitsou Nere';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Peau de Kitsou Nufeu';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Poils de Daïgoro';
UPDATE resource SET xp_pet = 0.01515 WHERE name = 'Patte d''Araknawa';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Oeuf d''Araknawa';
UPDATE resource SET xp_pet = 0.2 WHERE name = 'Brassard de Braconnier';
UPDATE resource SET xp_pet = 0.05 WHERE name = 'Peau de Cooleuvre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Dent magique de Cooleuvre';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Poils de Pandore';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Peau de Pandore';
UPDATE resource SET xp_pet = 0.03125 WHERE name = 'Poils de Pandikaze';
UPDATE resource SET xp_pet = 0.03226 WHERE name = 'Peau de Pandikaze';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Étoffe de Pandikaze';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Griffe de Pandikaze Vertige';
UPDATE resource SET xp_pet = 0.05 WHERE name = 'Poils de Pandule';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Peau de Pandule';
UPDATE resource SET xp_pet = 0.04167 WHERE name = 'Ambre de Bambouto';
UPDATE resource SET xp_pet = 0.04167 WHERE name = 'Feuille de Bambouto';
UPDATE resource SET xp_pet = 0.04167 WHERE name = 'Bois de Bambouto';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Racine Magique de Bambouto';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Feuille de Bambouto Sacré';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Ambre de Bambouto Sacré';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Bois de Bambouto Sacré';
UPDATE resource SET xp_pet = 0.0303 WHERE name = 'Racine de Bulbambou';
UPDATE resource SET xp_pet = 0.0303 WHERE name = 'Pousses de Bulbambou';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Écorce magique de Bulbambou';
UPDATE resource SET xp_pet = 0.03448 WHERE name = 'Racine de Bulbiflore';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Écorce magique de Bulbiflore';
UPDATE resource SET xp_pet = 0.07143 WHERE name = 'Racine de Bulbig';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Écorce magique de Bulbig';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Écorce magique de Bulbuisson';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Jeton du Bworker';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Peau de Bworkette';
UPDATE resource SET xp_pet = 0.01538 WHERE name = 'Noix de Cajou';
UPDATE resource SET xp_pet = 0.04545 WHERE name = 'Épaulette de Bwork';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Casque cassé de Bwork';
UPDATE resource SET xp_pet = 0.00518 WHERE name = 'Ficelle en Lin';
UPDATE resource SET xp_pet = 0.03571 WHERE name = 'Slip de Bwork Archer';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Scalp de Bwork Archer';
UPDATE resource SET xp_pet = 0.01961 WHERE name = 'Poils de Barbe du Bwork Mage';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Livre du Bwork Mage';
UPDATE resource SET xp_pet = 0.02857 WHERE name = 'Capsule Explosive';
UPDATE resource SET xp_pet = 0.04545 WHERE name = 'Ivoire';
UPDATE resource SET xp_pet = 1.55 WHERE name = 'Peau de Cochon de Farle';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Silex';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Pierre de Crystaloboule';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Pierre du Craqueleur';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Dent en Or du Craqueleur';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Fragment de Pierre Pointue';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Coeur de Craqueleur';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Oeil de Craquelope';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Langue de Craquelope';
UPDATE resource SET xp_pet = 0.07692 WHERE name = 'Fragment de Pierre Polie';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Méga Pierre du Craqueleur';
UPDATE resource SET xp_pet = 0.1 WHERE name = 'Charbon';
UPDATE resource SET xp_pet = 0.01053 WHERE name = 'Ongle de Chevaucheur de Karne';
UPDATE resource SET xp_pet = 0.02083 WHERE name = 'Dent de Karne';
UPDATE resource SET xp_pet = 0.04762 WHERE name = 'Noix de Pécan';
UPDATE resource SET xp_pet = 0.06667 WHERE name = 'Oreille de Douzdoa';
UPDATE resource SET xp_pet = 0.06667 WHERE name = 'Gant de Martoa';
UPDATE resource SET xp_pet = 0.06667 WHERE name = 'Oeil de Pikdoa';
UPDATE resource SET xp_pet = 0.06667 WHERE name = 'Casque de Sherpoa';
UPDATE resource SET xp_pet = 0.09091 WHERE name = 'Gelée de Dégelée';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Cuir de Déminoboule';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Poil de Gamino';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corne de Gamino';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Peau de Kraméléhon';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Peau de Mandrine';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Peau de Minoskito';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Bandelette du Mominotor';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Carapace de Scaratos';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Plume du Serpiplume';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Carniflore';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Boules de Kanniboul';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Poupée Vaudou Ark';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Poupée Vaudou Eth';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Poupée Vaudou Jav';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Poupée Vaudou Sarbak';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Poupée Vaudou Tam';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Plume de Domoizelle';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Feuille de Fourbasse';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Bourgeon de Fourbasse';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Fleur de Gloutovore';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Glouto Rhum';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Trukikol Mort';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Noix de Grokoko Traumatisée';
UPDATE resource SET xp_pet = 0.08333 WHERE name = 'Kokopaille';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Noix de Kokoko';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Tronc de Kokoko';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Tranche de Nodkoko';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Feuille de Tikoko';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Carapace Bleue';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Lait de Tortue';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Carapace Jaune';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Carapace Rouge';
UPDATE resource SET xp_pet = 0.16667 WHERE name = 'Carapace Verte';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Caleçon Mignon du Pirate';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Boulet de Canondorf';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Rhum de Qualité';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Bandeau de Nakunbra';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Canif Rouillé';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Croupion du Bitouf aérien';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Bave du Kaskargo';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Cloaque du Poolay';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Morceau de caleçon de Gourlo';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Maillot de corps de Barbroussa';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Chicot du Flib';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Foulard du Sparo';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Coccyx du Corailleur';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corail usé';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Nacre brute';
UPDATE resource SET xp_pet = 0.125 WHERE name = 'Pince de Crustorail';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corail Kouraçao';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corail Malibout';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corail Morito';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Corail Passaoh';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Bulbe Kouraçao';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Pétale Kouraçao';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Bulbe Malibout';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Bulbe Morito';
UPDATE resource SET xp_pet = 0.14286 WHERE name = 'Bulbe Passaoh';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Pétale Malibout';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Pétale Morito';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Pétale Passaoh';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Aile du Bitouf des Plaines';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Fragment de cerveau poli';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Plume de fesse du Kido';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Duvet du Kilibriss';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Moustache du Mufafah';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Dent de Bourbassingue';
UPDATE resource SET xp_pet = 0.33333 WHERE name = 'Bave de Ouassingue';
UPDATE resource SET xp_pet = 0.04545 WHERE name = 'Étoffe de Ouassingue';
UPDATE resource SET xp_pet = 0.1 WHERE name = 'Cuir de Ouassingue';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Estomac de Ouassingue';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Vieille Ventouse de Kralamoure';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Enfumoir Zoth';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Étoffe Zoth';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Jouet de Gamine Zoth';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Pierre Précieuse Zoth';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Calumet Zoth';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Boulier Zoth';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Sacrum magistral';
UPDATE resource SET xp_pet = 0.08333 WHERE name = 'Poil d''Abrakne';
UPDATE resource SET xp_pet = 0.03333 WHERE name = 'Ambre';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Écorce d''Abrakne Sombre';
UPDATE resource SET xp_pet = 0.03226 WHERE name = 'Écorce d''Abraknyde';
UPDATE resource SET xp_pet = 0.03226 WHERE name = 'Bourgeon d''Abraknyde';
UPDATE resource SET xp_pet = 0.03226 WHERE name = 'Racine d''Abraknyde';
UPDATE resource SET xp_pet = 0.25 WHERE name = 'Ambre d''Abraknyde';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Racine d''Abraknyde Sombre';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Bourgeon d''Abraknyde Sombre Irascible';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Racine d''Abraknyde Vénérable';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Masque Brisé d''Araknotron';
UPDATE resource SET xp_pet = 1.0 WHERE name = 'Masque Cassé d''Araknotron Irascible';
UPDATE resource SET xp_pet = 0.05882 WHERE name = 'Bois de Tronknyde';
UPDATE resource SET xp_pet = 0.5 WHERE name = 'Sourcils de Tronknyde';
UPDATE resource SET xp_pet = 0.0 WHERE name = 'Soie chatoyante';
UPDATE resource SET xp_pet = 0.00667 WHERE name = 'Eau calme';
UPDATE resource SET xp_pet = 0.0 WHERE name = 'Sang de Scorbute';
UPDATE resource SET xp_pet = 0.0 WHERE name = 'Artefact Pandawushu Eau';
UPDATE resource SET xp_pet = 0.0 WHERE name = 'Artefact Pandawushu Terre';
UPDATE resource SET xp_pet = 0.0 WHERE name = 'Artefact Pandawushu Feu';
UPDATE resource SET xp_pet = 0.0 WHERE name = 'Artefact Pandawushu Air';
UPDATE resource SET xp_pet = 0.0 WHERE name = 'Protection usagée du Bworker';
UPDATE resource SET xp_pet = 0.93 WHERE name = 'Peau de Don Dorgan';
UPDATE resource SET xp_pet = 0.82 WHERE name = 'Peau de Don Duss Ang';
UPDATE resource SET xp_pet = 0.96 WHERE name = 'Cuir de Porsalu';
UPDATE resource SET xp_pet = 0.81 WHERE name = 'Pierre de Granit';